version: "3"

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    ports:
      - "3001:3000"

  go-api:
    build:
      context: ../../../go/
      dockerfile: Dockerfile
    volumes:
      - ../../../go:/app
    ports:
      - "8080:8080"
    command: air -c .air.toml
